### ISSUE TITLE
Missing column descriptions for `flow.csv` in the Quickstart example.

### ISSUE THREAD

**Issue by d31v1vi5** [canmod/macpan2#95] opened 2023-06-23 16:11 UTC
I assume there have been changes to the `flows` description. As a result new columns `from_partition` ,`to_partition` ,`flow_partition` ,`from_to_partition` ,`from_flow_partition ,to_flow_partition` have been left undocumented. [HERE](https://canmod.github.io/macpan2/articles/quickstart#flows-csv)

<img width="700" alt="Screenshot 2023-06-23 at 12 08 25 PM" src="https://github.com/canmod/macpan2/assets/131555238/84017e2b-c85b-4d83-9cae-3ed524bef909">

**Comment by stevencarlislewalker** [comment] 2023-06-23 16:16
Thank you @d31v1vi5 !  Nothing has changed.  Those columns have been around for a long while.  Descriptions for these columns is slated for [this vignette](https://canmod.github.io/macpan2/articles/quickstart2.html).  You actually should be able to delete these columns and still have everything work as it is currently.  I would be grateful if you tested this and open a bug report if it doesn't work.

**Comment by stevencarlislewalker** [comment] 2023-06-23 16:18
A little more ... these additional columns only matter when your model has structure.  Models with structure have more than one column in the `Variables.csv` file.  Does this make sense @d31v1vi5 ?

**Comment by stevencarlislewalker** [comment] 2023-06-23 16:20
Duplicate of #60

**Closed by stevencarlislewalker** 2023-06-23 16:20 UTC

**Comment by d31v1vi5** [comment] 2023-06-23 16:23
Gotcha, thanks! Everything works as described.
